Lawliet/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using Lawliet.Models;
using Lawliet.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using Lawliet.Data;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task = System.Threading.Tasks.Task;
using Newtonsoft.Json;

namespace Lawliet.Controllers {
    public class AuthController : Controller {
        private readonly CachingService _cachingService;
        private readonly UserDataContext _context;

        public AuthController(CachingService cachingService, UserDataContext context) {
            _cachingService = cachingService;
            _context = context;
        }

        public async void Login() {
            await HttpContext.ChallengeAsync(GoogleDefaults.AuthenticationScheme, new AuthenticationProperties() {
                RedirectUri = Url.Action($"loggedIn")
            });
        }

        [HttpGet]
        public async Task<IActionResult> LoggedIn() {
            var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            var claim = result?.Principal?.Identities?.FirstOrDefault()?.Claims.Select(claim => new {
                claim.Issuer,
                claim.OriginalIssuer,
                claim.Type,
                claim.Value
            });

            var user = new User();
            claim?.ToList().ForEach(x => {
                switch (x.Type) {
                    case ClaimTypes.NameIdentifier:
                        user.Id = x.Value;
                        break;

                    case ClaimTypes.Name:
                        user.Name = x.Value;
                        break;

                    case ClaimTypes.Email:
                        user.Email = x.Value;
                        break;

                    case "urn:google:picture":
                        user.PictureUrl = x.Value;
                        break;
                }
            });

            user.CompletedTask = JsonConvert.SerializeObject(new List<string>());

            /*user.Topics.Add(new LessonTopic {
                Id = new Random().Next(10000, 100000).ToString(),
                ShortTitle = "Ядерная физика",
                Description = "Я́дерная фи́зика — раздел физики, изучающий структуру и свойства атомных ядер, а также их столкновения.",
                Url = "https://elar.urfu.ru/bitstream/10995/47002/1/978-5-7996-1992-3_2017.pdf",
                PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/CNO_Cycle.svg/1200px-CNO_Cycle.svg.png",
            });

            user.Topics.Add(new LessonTopic {
                Id = new Random().Next(10000, 100000).ToString(),
                ShortTitle = "Квантовая механика",
                Description = "Ква́нтовая меха́ника — фундаментальная физическая теория, которая описывает природу в масштабе атомов и субатомных частиц. Она лежит в основании всей квантовой физики, включая квантовую химию, квантовую теорию поля, квантовую технологию и квантовую информатику.",
                Url = "https://elar.urfu.ru/bitstream/10995/53042/1/978-5-321-02527-7_2017.PDF",
                PictureUrl = "https://new-science.ru/wp-content/uploads/2021/04/8281-2.jpg",
            });

            user.Topics.Add(new LessonTopic {
                Id = new Random().Next(10000, 100000).ToString(),
                ShortTitle = "Радиово́лны",
                Description = "Радиово́лны — электромагнитные волны с частотами до 3 ТГц, распространяющиеся в пространстве без искусственного волновода. Радиоволны в электромагнитном спектре располагаются от крайне низких частот вплоть до инфракрасного диапазона.",
                Url = "https://kpfu.ru/portal/docs/F1354445323/RWP26_Vol2_Final_compressed.pdf",
                PictureUrl = "https://image.slidesharecdn.com/random-130127210417-phpapp01/75/-14-2048.jpg?cb=1669073551",
            });*/

            var isUserInCache = _cachingService.GetObjectFromCache<User>(user.Id);
            if (isUserInCache != null) {
                HttpContext.Response.Cookies.Append("id", user.Id);
                await _cachingService.AddObjectFromCache(user);
                var previousPage = HttpContext.Request?.Cookies["previousPage"]?.Split('/');
                return (previousPage == null) ? RedirectToAction("Index", "Home") : RedirectToAction(previousPage[1], previousPage[0]);
            }

            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> LoggedIn(User user) {
            HttpContext.Response.Cookies.Append("id", user.Id);
            await _cachingService.AddObjectFromCache(user);
            var previousPage = HttpContext.Request?.Cookies["previousPage"]?.Split('/');
            return (previousPage == null) ? RedirectToAction("Index", "Home") : RedirectToAction(previousPage[1], previousPage[0]);
        }

        public async Task<IActionResult> Logout() {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Response.Cookies.Delete("id");
            return RedirectToAction("index", "home");
        }

        /*[HttpGet] public IActionResult LoginConfirmation() => View();

        [HttpPost]
        public IActionResult LoginConfirmation(bool isClickedLoginButton) {
            if (isClickedLoginButton) {
                return RedirectToAction("login", "auth");
            }
            return RedirectToAction("index", "home");
        }*/
    }
}

Lawliet/Controllers/ExcelController.cs
using ClosedXML.Excel;
using Lawliet.Models;
using Microsoft.AspNetCore.Mvc;
using System.Web;
using Microsoft.EntityFrameworkCore.Metadata;


namespace Lawliet.Controllers {
    public class ExcelController : Controller {

        [HttpGet]
        public IActionResult Index(object _) => View();

        [HttpPost]
        public IActionResult Index() 
        {
            List<StudentViewModel> students = new List<StudentViewModel>();
            using (XLWorkbook workBook = new XLWorkbook(HttpContext.Request.Form.Files[0].OpenReadStream())) 
            {
                foreach (IXLWorksheet worksheet in workBook.Worksheets) 
                {
                    foreach (IXLRow row in worksheet.RowsUsed().Skip(1)) 
                    {
                        StudentViewModel student = new StudentViewModel();
                        var fio = row.Cell(1).Value.ToString().Split(' ');
                        student.LastName = fio[0];
                        student.FirstName = fio[1];
                        student.Patronomyc = fio[2];
                        student.Group = worksheet.Name;

                        student.Ratings.Add(Convert.ToInt32(row.Cell(2).Value.ToString()));
                        student.Ratings.Add(Convert.ToInt32(row.Cell(3).Value.ToString()));
                        student.Ratings.Add(Convert.ToInt32(row.Cell(4).Value.ToString()));
                        student.Ratings.Add(Convert.ToInt32(row.Cell(5).Value.ToString()));
                        students.Add(student);
                    }
                }
            }
            return View(students);
        }
    }
}

Lawliet/Controllers/ProfileController.cs
using Lawliet.Data;
using Lawliet.Models;
using Lawliet.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace Lawliet.Controllers
{
    public class ProfileController : Controller {
        private readonly UserDataContext _context;
        private readonly CachingService _cachingService;

        public ProfileController(UserDataContext context, CachingService cachingService) {
            _context = context;
            _cachingService = cachingService;
        }

        [HttpGet]
        public IActionResult Edit(string id) {
            ViewBag.UserId = id;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(User user) {
            DataRepository<User> repository = new DataRepository<User>(_context);
            User _user = repository.GetWithInclude(x => x.Id == user.Id, z => z.Topics).First();

            repository.Remove(_user);

            _user.AboutMe = user.AboutMe;
            _user.Email = user.Email;
            _user.Status = user.Status;
            _user.Name = user.Name;
            _user.AboutMe = user.AboutMe;
            _user.Group = user.Group;

            await repository.CreateAsync(_user);
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Index() {
            /*DataRepository<User> repository = new DataRepository<User>(_context);
            var user = repository.GetWithInclude(x => x.Id == HttpContext.Request.Cookies["id"], z => z.Topics).ToList();*/

            var tasks = _context.StudentTasks.Where(x => x.AuthorId == HttpContext.Request.Cookies["id"]);
            var user = _context.Users.Where(x => x.Id == HttpContext.Request.Cookies["id"]).FirstOrDefault();
            if(user == null) {
                return RedirectToAction("Login", "Auth");
            }

            user.StudentTasks = tasks.ToList();
            return View(user);
        }
    }
}

Lawliet/Views/Shared/_Layout.cshtml
@using Lawliet.Data;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lawliet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lawliet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lawliet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная страница</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index">Профиль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Excel" asp-action="Index">Excel статистика</a>
                        </li>

                        @if (Context.User.Identity.IsAuthenticated) {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">-> Выйти</a>
                            </li>
                        } else {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">-> Войти</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Lawliet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>